# Site settings
title: Capítulo ACM
email: acm@uc.cl
username: acm-uc
description: "Somos el capítulo estudiantil de la ACM de la Pontificia Universidad Católica de Chile.
  Nuestro objetivo es promover la Computación"
baseurl: ""
url: "http://acm-uc.github.io"

# Build settings
permalink: "/:categories/:short_year/:i_month/:i_day/:title"
markdown: kramdown
